### ISSUE TITLE
Can't start new processes on MacOS with .app

### ISSUE THREAD

**Issue by idontusenumbers** [libgdx/packr#161]
When using ProcessBuilder, one cannot start a new process within a .app packaged by packr. The same code, run from the same embedded JRE directly, actually can start the processes.

starting the process throws an IOException with error number 2 or 20, `error=2, No such file or directory`, both seem to be from posix.

**Comment by karlsabo** [comment]
This sounds like an issue what was fixed for newer versions of Java. The libjli.dylib was moved in recent JREs. Please try the latest version of packr which is tested against Java 8, 11, and 14.

**Comment by idontusenumbers** [comment]
I downloaded `packr-all-2.7.0.jar` and `OpenJDK14U-jdk_x64_mac_hotspot_14.0.2_12.tar.gz`, ran `packr`, and still get:
```
error=2, No such file or directory
```

**Comment by idontusenumbers** [comment]
For some background, I'm using ProcessBuilder to start various audio encoders, `oggenc`, `lame`, etc

**Comment by karlsabo** [comment]
Do you have any other logging information? Have you run with `-c --verbose`? Is this failure occurring in Java code when you do Processbuilder#start?

**Comment by idontusenumbers** [comment]
Yes, java code from `ProcessBuilder.start()`
```
cosmotic@Hank~/Documents/Programs/Java/NoiseCaster/:NoiseCasterTest.app/Contents/MacOS/NoiseCaster -c --verbose
Changing working directory to /Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources ...
Loading JVM runtime library ...
fileSearch found libjli! filename=jre/lib/libjli.dylib, lastFileSearch=
Loading libjli=/Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/jre/lib/libjli.dylib
Passing VM options ...
isZgcSupported()=1, hasJsonValue(jsonRoot, "useZgcIfSupportedOs", sajson::TYPE_TRUE)=0
Passing VM options:
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # NoiseCaster.jar
Invoking static net.obive.noisecaster.NoiseCaster.main() function ...
NoiseCaster version 0.12
http://obive.net 
Java version 14.0.2

Found /Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/oggenc, but it couldn't be used: Cannot run program "/Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/oggenc": error=2, No such file or directory

java.io.IOException: Cannot run program "/Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/oggenc": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.obive.noisecaster.encoders.ExternalEncoder.tryPath(ExternalEncoderFactory.java:148)
    [...]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)

```

**Comment by karlsabo** [comment]
Does the file `/Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/oggenc` exist? Can you run it from a terminal?

**Comment by idontusenumbers** [comment]
```
cosmotic@Hank~/Documents/Programs/Java/NoiseCaster/:/Users/cosmotic/Documents/Programs/Java/NoiseCaster/NoiseCasterTest.app/Contents/Resources/oggenc --version
oggenc from vorbis-tools 1.4.0
```

**Comment by karlsabo** [comment]
What other options are you passing to ProcessBuilder? Maybe it's a work directory issue.

**Comment by idontusenumbers** [comment]
I don't think I'm doing anything unusual:
```
private boolean tryFile(String pathname) {
	File file = new File(pathname);
	if (file.exists() && file.isFile()) {
		if (tryPath(pathname, true))
			return true;
	}
	return false;
}

private boolean tryPath(String pathname, boolean isFile) {
	try {
		ProcessBuilder pBuilder = new ProcessBuilder(pathname, "--help");
		pBuilder.redirectErrorStream(true);
		Process process = pBuilder.start();

		if (isExpectedProcess(new Scanner(process.getInputStream())))
			return true;
		else
			System.err.println("Found " + pathname + ", but it didn't produce the expected output");
	} catch (Exception ex) {
		if (isFile) {
			System.err.println("Found " + pathname + ", but it couldn't be used: " + ex.getMessage());
			ex.printStackTrace();
		}

	}
	return false;
}
```

As you can see, it's already passing a file existence check, that and the fact that the paths are absolute based on the error messages, I don't think it's a path issue.

All the same code works if I run the same jar using `java -jar`, it also works fine after using `jar2app` which produces a `.app` containing `JavaAppLauncher`.

I'm not familiar with native code on macos but I suspect its a sandboxing thing or however the java process is setup from packr's wrapper.

**Comment by karlsabo** [comment]
I haven't seen anything in Packr that should cause a problem. Let's find out, have you tried:

1. `mv NoiseCasterTest.app NoiseCasterTest_app`
2. `cd NoiseCasterTest_app/Resources`
3. `../MacOS/NoiseCasterTest` 
   * Make sure you use whatever you made the executable name here.

This will help rule out any odd behavior from being in a "special" .app directory.

If this fails, try something simple, like a ProcessBuilder with `ls` or some other basic command.

**Comment by idontusenumbers** [comment]
After further investigation, it seems to be an issue with code signing. I swapped the JRE out with one I used from `jar2app` (which itself was probably using the system JRE), and it seems to work fine.

When I try to run the jar2app version with the JRE I was using from the packr version of the app, I saw this in Console.app:
```
default	17:36:33.066006 -0500	launchservicesd	MacOS error: -67062
```


For what it's worth, here are the results from your queries:

No luck renaming the .app to _app:
```
cosmotic@Hank~/Documents/Programs/Java/NoiseCaster/build/Mac deploy/:mv NoiseCasterTest.app/ NoiseCasterTest_app/
cosmotic@Hank~/Documents/Programs/Java/NoiseCaster/build/Mac deploy/:cd NoiseCasterTest_app/Contents/Resources/
cosmotic@Hank~/Documents/Programs/Java/NoiseCaster/build/Mac deploy/NoiseCasterTest_app/Contents/Resources/:../MacOS/NoiseCaster 
NoiseCaster version 0.12
http://obive.net 
Java version 14.0.2

Found /Users/cosmotic/Documents/Programs/Java/NoiseCaster/build/Mac deploy/NoiseCasterTest_app/Contents/Resources/oggenc, but it couldn't be used: Cannot run program "/Users/cosmotic/Documents/Programs/Java/NoiseCaster/build/Mac deploy/NoiseCasterTest_app/Contents/Resources/oggenc": error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/cosmotic/Documents/Programs/Java/NoiseCaster/build/Mac deploy/NoiseCasterTest_app/Contents/Resources/oggenc": error=2, No such file or directory
```

I tried sticking this in at startup:
```
try {
	ProcessBuilder pBuilder = new ProcessBuilder("/bin/pwd");
	pBuilder.redirectErrorStream(true);
	Process process = pBuilder.start();
	System.out.println(new Scanner(process.getInputStream()).nextLine());
} catch (IOException e) {
	e.printStackTrace();
}
```
and got:
```
Java version 14.0.2

java.io.IOException: Cannot run program "/bin/pwd": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.obive.noisecaster.NoiseCaster.main(NoiseCaster.java:117)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:250)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 2 more
```
Running from IDEA/jar I get:
```
Java version 11.0.2

/Users/cosmotic/Documents/Programs/Java/NoiseCaster
```

**Comment by karlsabo** [comment]
I'm seeing the same thing on my Mac. I tried `new ProcessBuilder("java", "-version").inheritIO().start();`. Let me know if you have any luck signing and notarizing the executable.

**Comment by karlsabo** [comment]
I found the issue, you need to make sure `jre/lib/jspawnhelper` has the execute bit set. Reference: <https://stackoverflow.com/questions/53113127/java-runtime-exec-fails-to-run/55091040>

**Comment by idontusenumbers** [comment]
Oh my, I was so close! I chmod'ed all those in the bin dir, but nothing in the lib dir. Thank you so much for your research on this matter!

Might it make sense for packr to do the needed chmods upon decompressing the JRE?

**Comment by karlsabo** [comment]
I updated packr to search for jspawnhelper and set it to executable. You can try the latest packr, available at <https://github.com/libgdx/packr/packages/394128>
