### ISSUE TITLE
Windows 10 Scaling 

### ISSUE THREAD

**Issue by someguy233** [libgdx/packr#83]
My libgdx game gets stretched larger when my desktop scaling is set to 125% in Windows 10. Happens when I set the game to fullscreen.

Running the JAR directly maintains the correct size.

**Comment by code-disaster** [comment]
I suspect the executable not setting "DPI awareness" (in code or by application manifest) to be the cause for this. Can you try to replace your packr executable with the ones I pushed to [this branch](https://github.com/code-disaster/packr/tree/windows-dpi-aware/src/main/resources)? I'd like to verify if this actually fixes the issue before I merge it to master.

**Comment by JoelOtter** [comment]
Hi @code-disaster - I'm still seeing this issue with the latest version of packr (2.0.0-SNAPSHOT, I believe). I'm using LWJGL2.

Running the JAR directly works fine, as does going to properties on the executable and checking 'override high DPI scaling behavior'.

I'm running packr on macOS, if that makes any difference.

Thanks! Love this tool.

**Comment by someguy233** [comment]
Same here, on windows 10. 

It works fine with LWJGL3.

But if you want to use LWJGL2, you can add the following to vm args in config.json

-Dsun.java2d.dpiaware=true

**Comment by JoelOtter** [comment]
Thanks @someguy233 - this fixed the problem for me!
